# EMG path
EMGdata_savePath: null  # Where we save the output EMG. If None, saved in the same directory as the original recording
overwrite: False  # Do we recompute and overwrite preexisting EMG data

# Source data
LFP_binPath: ''  # path to recording
LFP_datatype: 'SGLX'  # Datatype of recording
LFP_downsample: null # sf of LFP used when computing xcorr. 
LFP_chanList: [] # List of loaded channels. See sleepscore documentation. eg: (SGLX) ["LF0;384", "LF1;385"] or (TDT) [LFPs-1, LFPs-2]

# Filtering (params passed to scipy.signal.iirdesign)
wp: [300, 600]
ws: [275, 625]
gpass: 1
gstop: 20
ftype: 'butter'

# Algorithm parameter
sf: 20  # output EMG sf (Hz)
window_size: 25.0  # Window size in ms for xcorr computing
